baseURL = "https://leocarvalho.dev/"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"
title = "Leo Carvalho"
theme="hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[menu]
    [[menu.main]]
        name = "Blog"
        weight = 2.0
        url  = "/posts/"
    [[menu.main]]
        name = "About"
        weight = 1.0
        url = "/about/"